# Generated by Django 4.1.1 on 2022-09-20 17:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/images', verbose_name='Image Field')),
                ('event_dt', models.DateTimeField(null=True, verbose_name='Auction Ends at')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField(verbose_name='Bid Price')),
                ('bid_at', models.DateTimeField(auto_now=True, verbose_name='Bid Created At')),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Bid By')),
            ],
        ),
    ]
