# Generated by Django 4.1.1 on 2022-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_created_at_ipandrequests_last_request_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAndIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(verbose_name='IP Address')),
                ('last_request_time', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('req_counter', models.IntegerField(verbose_name='Requests left')),
            ],
        ),
        migrations.DeleteModel(
            name='IPandRequests',
        ),
    ]
