# Generated by Django 4.1.1 on 2022-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requestandip_delete_ipandrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestandip',
            name='isBanned',
            field=models.BooleanField(default=False, verbose_name='Is Banned'),
            preserve_default=False,
        ),
    ]
