# Generated by Django 4.1.1 on 2022-09-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_requestandip_isbanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestandip',
            name='isBanned',
        ),
    ]
