# Generated by Django 4.1.1 on 2022-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_requestandip_isbanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
