# Generated by Django 4.1.1 on 2022-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval Status'),
        ),
    ]
