# Generated by Django 4.1.1 on 2022-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Banned'),
        ),
    ]
